- src/dashboard.ts
Fix the SQL query to use the timeline table to determine the list if benchmarks.
This should work for "a while".
Not sure what to do when the timeline hast too much data.
But, we can look into that once it comes to it.
> Use timeline to get benchmarks, instead of checking all measurements

- .eslintrc.js
- src/api.ts
- src/db.ts
- src/db/db.sql
- src/db/migration.002.sql
- src/perf-tracker.ts
- tests/db-setup.test.ts
The denoise information contains details on system settings that influence noise level for measurements.
This change does not yet use or display this information yet.
This PR also disables lint rules for explicit any types and skipped tests.
> Added database support for denoise information

- resources/plots.js
- resources/render.js
- src/dashboard.ts
- tests/dashboard.test.ts
Until now, we did show everything on a single plot, which is worse than useless.
Now the plots are split out, and the results are limited to the last 100 data points.
> Show benchmarks separately on main page and only last 100 results

- .eslintrc.js
- .github/workflows/ci.yml
- resources/plots.js
- resources/render.js
- src/api-validator.ts
- src/dashboard.ts
- src/db.ts
- src/index.ts
- src/perf-tracker.ts
- src/templates.ts
- tests/dashboard.test.ts
- tests/db-setup.test.ts
- tests/db-testing.ts
- tests/report.test.ts
- tests/single-requester.test.ts
This will allow us to more easily test interaction with R scripts.
Before, the tests used a separate DB just for a single test.
Now, things are more uniform, and DB initialization and release is done more consistently.
- implement incomplete and previously skipped tests
- remove eslint setting to ignore skipped tests
- adds a new eslint setting to limit line length to 80 chars.
> Use separate databases for testing

- src/db.ts
- src/db/db.sql
- src/db/migration.002.sql
- src/stats/timeline.R
- src/views/rebenchdb.R
Updating the time line has been a very expensive operation, because we queried the measurement table with HAVING COUNT(..), GROUP BY, etc.
This PR replaces this by using a separate table, where we keep track of the experiments that have need data, and thus, communicate directly, with the R script, what needs calculation.
Then, requesting the data becomes significantly cheaper.
However, there's probably room for further improvements, since currently, the query takes still 10seconds on rebench.stefan-marr.de.
This PR also uses the `ON CONFLICT` versions of queries to avoid previously problematic things, and either ignore existing entries in the database, or update them.
For measurements, the DB is supposed to be append only.
So, we ignore them.
For the timeline, we simply update them with …
> Speedup timeline compute

- src/db.ts
- src/index.ts
- src/perf-tracker.ts
This change may slightly increase the robustness of the system.
It also uses slightly more telling data for the performance recording of ReBenchDB operations.
The non-telling data confused me into a ghost chase.
> Type DB results and reject data without startTime

- .eslintrc.js
- package-lock.json
- package.json
- resources/plots.js
- resources/render.js
- src/api.ts
- src/dashboard.ts
- src/db.ts
- src/db/db.sql
- src/db/migration.002.sql
- src/github.ts
- src/index.ts
- src/templates.ts
- src/util.ts
- tests/dashboard.test.ts
- tests/db-setup.test.ts
- tests/db-testing.ts
- tests/report.test.ts
Add support for projects to configure a baseBranch, which can be used to automatically determine comparisons.
Detailed discussion and design reasons are documented in #30.
Summary creation is triggered explicitly when an experiment is marked as completed.
The GitHub interaction relies on GitHub's rest.js.
Cleanups:
- make quote use more consistent
- extract robustPath helper
- add siteConfig and dbConfig in util.ts
- use a promise version of execFile
- for dashboard.test add second experiment be reusing adapted test data
Closing #30.
> Post Summary on GitHub

- src/views/plots.R
The fast/slower colors were switched on the summary plots, which is confusing.
Everything over 1 should be indicated with the slower color, and everything under one with the faster color.
1 refers here to the run-time ratio, where lower is better.
> Fix the color in summary plots

- resources/render.js
- src/dashboard.ts
- src/db.ts
- src/index.ts
This PR obtains the correct project name when composing the URL for the comparison view.
It also checks that the given project has the given revisions. If it doesn't find them, it reports an error.
This PR resolves #34.
> Use correct project name for compare view and check data exists

- resources/render.js
A tiny change, just to not get into the situation mentioned in #10, i.e., looking at a compare view with `undefined` and `undefined` as revision.
> Don’t go to compare view when no revision was selected

- package-lock.json
- package.json
- src/github.ts
When updating the `@octokit/auth-app` package beyond v3.0.0, the `id` field in the auth details is not longer supported, but must be `appId`.
> Fix GitHub authentication

- src/dashboard.ts
The link didn't contain the full URL.
This was broken when trying to fix linter issues. sigh
> Fix the link pointing to full report that is posted to GitHub

- README.md
- src/views/plots.R
This needs the server to have the font, otherwise, we’ll still end up with some obscure font being hardcoded into the SVG that’s not widely available.
> Set Arial as standard font, since it’s available in most browsers

- resources/style.css
- src/index.ts
- src/views/compare.html
- src/views/somns.R
This moves the warmup tables where we need them to assess the results of a particular benchmark.
Having them in a separate section at the end of the report was mostly because of KnitR restrictions.
Since we aren't using KnitR any longer, having them inline seems better.
Initially, the warmup plots won't be shown.
Instead, there are buttons to expand the whole section, or the specific plot.
> Move warmup plots into table with inline plots

- .gitignore
- resources/style.css
- src/dashboard.ts
- src/views/common.R
- src/views/compare.html
- src/views/plots.R
- src/views/somns.R
- tests/report.test.ts
This PR adds comparisons between executors in addition to the normal comparison between versions.
It's a rewrite/extension of the ad hoc comparison implemented on #46.
Though, instead of relying on a naming heuristic, this identifies suitable comparisons based on the available executors and suites.
It also adds a navigation bar for the now quite a bit longer reports.
The table contains the measurements per benchmark.
To attribute the results to the relevant executors, the common prefix of the executor names is removed.
This works quite well with names like `SOM-interp` and `SOM-jit` for instance.
This resolves #60.
Other changes:
- make somns.R easier to use in RStudio
- replace the custom backtrace by the one provided by rlang from the tidyverse
> Add Comparisons between Executors

- package.json
This encodes the required minimum Node.js version.
I don't really know what the supported minimum is, so, I'll go with what I have locally.
@HumphreyHCB does this work for you?
> Add required node version to package.json

- resources/style.css
- src/views/compare.ts
- src/views/rebenchdb.R
- src/views/somns.R
Display the details of the environment in which a benchmark ran.
The info is shown as popover on an icon, similar to the command line.
- Added HTML & CSS for Environment Button
- Changes to sql to capture Environment information
- SQL and Button Changes to capture environments
- Added popover CSS & formatted Text for environment
All benchmarks now have an addition information button (A CPU icon). It will display:
Hostname - Name of the machine this specific benchmark was run on
OS type – the operating system of the machine
Memory – the amount of the memory the machine has
CPU – the type of CPU the machine has
Clockspeed – the Clock speed of the CPU
The List of Environments is queried once per comparison and stored in memory, which should result in a minimal effect on …
> Implemented environment information Button

- src/stats/timeline.R
- src/views/plots.R
- src/views/somns.R
After looking at the execution in a profiler, there were a few things that stuck out as unusual/undesirable.
The magrittr pipe is a little slower than R's builtin pipe operator, which is now available (wasn't we this project started).
`droplevels()` also seems to take enough time to warrant more careful use.
Instead of using it everywhere, I am now using it only when I want to look at the levels, for instance to iterate over them.
The investigation also revealed that up to 20% of run-time is spent on checking whether the terminal can represent colors, which seems a lot of redundant work, but that's an issue in the rlang package: 
https://github.com/r-lib/rlang/issues/1444
As a minor change, this fixes the script for running from the command-line, which was broken after introducing …
> Prefer R's bultin pipe and use droplevels() more strategically to improve performance

- resources/style.css
- src/views/compare.html
This PR improves how the page looks on smaller, more narrow screens/windows.
Specifically, it:
- makes sure that the change list fits exactly on the screen without scrolling, when accessing `/ProjectName` 
- it improves the handling of the navigation. Instead of being in the way, it's hidden on narrow screens, but can be shown before the actual content when desired
@HumphreyHCB would be great if you could review on Monday.
> Improve Space use on Mobile

- resources/style.css
- src/views/compare.html
- src/views/compare.ts
- src/views/somns.R
This adds an icon at the top, which will show the benchmark names, grouped as found in the report.
It also adds buttons to select all or none of the benchmarks.
@HumphreyHCB I'll rebase this on master after the other bits are merged. So, there are still changes in here currently, that are part of a separate PR. Would be great if you could have a look at these changes, too.
> Add support to filter by selecting/unselecting benchmarks in the change view

- src/db/migration.003.sql
This is a missing migration file for PR #78, which added the recording of profiling information and the `ProfileData` table.
This is mostly of historic interest, but was clashing with another migration file.
> Added missing migration file (PR #78 adding profiling information)

- package.json
- resources/style.css
- src/api.ts
- src/dashboard.ts
- src/db.ts
- src/index.ts
- src/views/compare.html
- src/views/compare.ts
- src/views/filter.ts
- src/views/header.html
- src/views/plots.ts
- src/views/render.ts
- src/views/timeline.html
- src/views/timeline.ts
- src/views/util.ts
- tests/dashboard.test.ts
- tests/ui.test.ts
The main motivation of this change is to improve the performance of the timeline view.
Since there are hundreds of timelines, Plotly.js ends up being very slow.
Because it uses SVG, it takes much more resources than uPlot, which renders directly on the canvas, and which we used already in the comparison view.
The other goal was the bring the different ways of requesting "over time" data closer together.
There are:
- the timeline view
- the timeline plots on the comparison view
- and the result view on the main page and project page
The code now uses mostly the same data format, except for the result view, where we avoid transferring arrays filled with nulls and indexes to minimize the data transfer.
- added the same filter mechanism as on comparison view
- added the navigation features as …
> Use uPlot also for timeline and for the result view of projects

- src/dashboard.ts
- src/db.ts
- src/db/db.sql
- src/db/migration.005.sql
- src/index.ts
- src/views/index.html
- src/views/index.ts
- src/views/project.html
- src/views/project.ts
- src/views/render.ts
- tests/dashboard.test.ts
The PR resolves #107.
Inspired by GitHub and GitLab, the new URL structure is:
- `/Project-Slug` - the project page
- `/Project-Slug/data` - for the data page
- `/Project-Slug/data/1836` - to generate the download
- `/Project-Slug/timeline`
- `/Project-Slug/compare/sha1..sha2`
The old URLs remain supported, since people have access to them on various archives/Slack instances, but the redirect to the new ones.
This introduces a `slug` column in the project table, which is a converted version of the name, replacing all non-trivial characters ([^0-9a-zA-Z-]) with a dash `-`. One may want to relax that in the future...
Slugs are always compared case-insensitively.
If a project isn't found, we show now a proper error.
Much of the client-side rendering is now moved to the server to reduce the …
> Redesign user-visible URLs

- src/dashboard.ts
- src/db.ts
- src/index.ts
- src/perf-tracker.ts
- src/util.ts
- tests/cache-validity.test.ts
- tests/db-testing.ts
This is an attempt to improve the performance of the front page by caching the statistics at the bottom as well as the over-time performance results for the self-tracking.
The caching mechanism is more general, but only applied to `dashResults` and `dashStatistics` for now.
Though, there's another caching mechanism already, but that's only used for recording data.
This PR also changes how `completeRequest` is used for recording self-tracking performance.
Instead of awaiting it results, we only trigger it, but do not await it any longer.
This seems to improve performance in some cases at least on my local machine.
> Cache statistics and self-tracking results on front page for at least 5min

- src/views/plots.ts
This gives a more consistent visual image.
And yes, line plots are theoretically not the right plot type to start with…
> Do draw lines across data gaps in timeline plots

- .gitlab-ci.yml
- Dockerfile
- Dockerfile.rebench
- rebench.conf
- render-report.sh
- src/api.ts
- src/benchmarks/benchmark.ts
- src/benchmarks/compute-timeline.ts
- src/benchmarks/fetch-results.ts
- src/benchmarks/harness.ts
- src/benchmarks/rebenchdb-benchmark.ts
- src/benchmarks/render-report.ts
- src/benchmarks/store-results.ts
- src/dashboard.ts
- src/db.ts
- src/db/db.sql
- src/stats/get-exp-data.R
- src/stats/timeline.R
- src/views/rebenchdb.R
- src/views/somns.R
- tests/db-testing.ts
- tsconfig.json
This PR adds the necessary setup and benchmarks to track performance of the following operations:
- storing results from a benchmarking client
- fetching results for display on the line chart (main page, self tracking)
- computing timeline statistics
- rendering a report with differences
The benchmarking is setup using Docker, or rather podman, as a root-less, daemon-less alternative. The goal was to have a self-contained setup, that does not require installing and managing Postgres on the benchmarking machine.
The benchmark harness is taken from the AreWeFastYet project.
All benchmarks come with three different workload sizes, small, medium, and large, which scales the run-time of the from few milliseconds to minutes.
- rearrange dockerfile to maximize the use of caching, avoid including …
> Implement Benchmarks and continuous Performance Tracking using ReBench

- src/db/migration.006.sql
- tests/db.test.ts
This completes the changes started in #115.
While just a theoretical issue, including the expId into the unique constraint prevents issues with unrelated experiments not being able to record their trial information.
This is in practice very unlikely to be an issue since the start time is part of the unique constraint. Though, for benchmarking it was noticed, and felt wrong not to fix it.
> Add tests and a migration for the added expId in Trial’s unique constraint

- src/dashboard.ts
- tests/dashboard.test.ts
- tests/db-setup.test.ts
- tests/db-testing.ts
- tests/db.test.ts
The results were not correctly ordered.
The didn't consider invocation ordering, and were ordered newest to oldest, which is not what's expected.
Add a bunch of tests to make sure we consider most permutations possible.
> Fix ordering of the results returned by dashResults, i.e., the results view on the index/project pages

- .gitlab-ci.yml
This makes sure we have a predictable hostname for recording results in ReBenchDB.
> Set the hostname in the GitLab CI setup for running the image

- package-lock.json
- resources/style.css
- src/api.ts
- src/dashboard.ts
- src/db.ts
- src/index.ts
- src/views/plots.ts
- src/views/render.ts
- src/views/timeline.html
- src/views/timeline.ts
- tests/dashboard.test.ts
This PR includes a number of usability improvements for the timeline view:
- show a tooltip with the commit details when hovering over a datapoint
- indicate parameters to the benchmark in the benchmark name, instead of solely in the command line
- make the benchmark name a link, which is revealed on hover to be able to deep-link to a specific plot
> Improve Timeline View

- src/dashboard.ts
- src/db.ts
- src/db/db.sql
- src/db/migration.009.sql
Currently, GitHub comments would have been always created when the project seemed to be hosted on GitHub, though, for some projects that's not desired.
Using the new `githubNotification` column in the project database table, they can be disabled.
> Added a project setting to disable github notifications

- Dockerfile
- Dockerfile.rebench
The docker image didn't build anymore, because it got a 404 downloading some dependency.
So, I thought, we may as well upgrade the base image to the latest Debian.
Interestingly, Python doesn't like `pip install` anymore: https://peps.python.org/pep-0668/
Not sure that's really useful for a docker image and/or ReBench, so, I'll just override the behavior with `pip install --break-system-packages`
> Fix the Docker image

- src/backend/compare/html/stats-row-across-exes.html
- src/backend/compare/html/stats-row-across-versions.html
- src/backend/compare/html/stats-row.html
- src/backend/compare/html/stats-summary.html
- src/backend/compare/html/stats-tbl-header.html
- src/backend/compare/html/stats-tbl.html
- src/backend/compare/prep-data.ts
- src/frontend/compare.ts
- src/shared/data-format.ts
- src/shared/helpers.ts
- src/shared/view-types.ts
- tests/backend/compare/charts.test.ts
- tests/backend/compare/compare-view.test.ts
- tests/data/expected-results/compare-view/compare-versions.html
- tests/data/expected-results/compare-view/stats-row-across-exes.html
- tests/data/expected-results/compare-view/stats-row-across-version.html
- tests/data/expected-results/compare-view/stats-row-exe.html
- tests/data/expected-results/compare-view/stats-row-version-one-criteria-missing.html
- tests/data/expected-results/compare-view/stats-row-version.html
- tests/data/expected-results/compare-view/stats-summary.html
- tests/data/expected-results/compare-view/stats-tbl-header.html
- tests/data/expected-results/compare-view/stats-tbl.html
- tests/data/expected-results/stats-data-prep/compare-view-jssom.html
- tests/data/expected-results/stats-data-prep/compare-view-tsom.html
- tests/views/helpers.test.ts
This filters the criteria that are displayed in the overview and in the tables for the comparison view based on the criteria for which we have non-zero data.
So, we filter out data that is always zero to avoid clutter.
And we show the columns for all criteria.
The overview statistics are percentage of change, and now labeled as such.
This PR resolves the following issues:
- #143
- #149
- #153
It also fixes the counting of run configurations, which previously multiplied the result by the number of found criteria.
> Fix overview labelling and base table columns on available data

- src/backend/compare/compare.ts
- src/backend/compare/db-data.ts
- src/backend/compare/html/stats-row-buttons-info.html
- src/backend/compare/prep-data.ts
- src/backend/db/db.ts
- src/backend/db/has-profile.ts
- src/backend/db/types.ts
- src/backend/perf-tracker.ts
- src/frontend/compare.ts
- src/frontend/plots.ts
- src/index.ts
- src/shared/data-format.ts
- src/shared/view-types.ts
- tests/backend/compare/compare-view.test.ts
- tests/backend/compare/db-data.test.ts
- tests/data/expected-results/compare-view/compare-versions.html
- tests/data/expected-results/compare-view/stats-row-button-info.html
- tests/data/expected-results/compare-view/stats-row-exe.html
- tests/data/expected-results/compare-view/stats-row-version-one-criteria-missing.html
- tests/data/expected-results/compare-view/stats-row-version.html
- tests/data/expected-results/compare-view/stats-tbl.html
- tests/data/expected-results/stats-data-prep/compare-view-jssom.html
- tests/data/expected-results/stats-data-prep/compare-view-tsom.html
- tests/shared/data-format.test.ts
In this PR, we combine data in the comparison view for multiple experiment ids and trial ids.
We essentially stop using expId and trialId to distinguish data sets from now on.
Instead, we rely solely on commit ids.
The user interface of ReBenchDB is all around commit ids, so, it makes sense to combine multiple experiments that provide data for a specific revision, and the assumption is that there's no change in the setup, environment, benchmarks, or executors between different experiments on the same source revision.
As a consequence, the plots to visualize warmup data may need to show data from multiple trials/experiments.
The profiling info now can be a list of profiles, which are all shown under the corresponding revision.
We do not track invocation numbers anymore in the data for …
> Combine measurements from multiple trials and experiments for the same code revision

- src/backend/compare/html/stats-row-across-exes.html
- src/backend/compare/html/stats-row-across-versions.html
- src/backend/compare/prep-data.ts
- src/shared/stats.ts
- tests/shared/stats.test.ts
This makes the new comparison view a bit more robust to odd data sets.
Specifically, it enables to render:
http://localhost:33333/CSOM/compare-new/19976d337bfa93eb337d9e039c2bc0dac206b76e..e85807751395941ae09f659a4580fe9599cc0029
The displayed results are not ideal, but given the odd data set, it’s better to render at least something instead of just fail with some assertion and an internal server error.
> Make data set render

- resources/style.css
- src/backend/compare/db-data.ts
- src/backend/compare/html/index.html
- src/backend/compare/html/stats-row.html
- src/backend/compare/prep-data.ts
- src/backend/db/db.ts
- src/shared/view-types.ts
- tests/backend/compare/prep-data.test.ts
- tests/data/expected-results/compare-view/stats-row-version-missing.html
- tests/data/expected-results/compare-view/stats-row-version-one-criteria-missing.html
- tests/data/expected-results/stats-data-prep/compare-view-jssom.html
- tests/data/expected-results/stats-data-prep/compare-view-tsom.html
- allow best-effort comparison with changing runId, indicate as possibly invalid with a warning
- make sure we discard data that's not a comparison across versions
- improve wording around mismatching configurations
This resolves #152.
> Fix failing comparisons on new comparison view

- src/backend/compare/html/index.html
- src/backend/compare/prep-data.ts
- src/shared/view-types.ts
- tests/backend/compare/compare-view.test.ts
- tests/data/expected-results/stats-data-prep/compare-view-jssom.html
- tests/data/expected-results/stats-data-prep/compare-view-tsom.html
This adds the overview table for missing data, which we had in the old comparison view.
The PR also removes the case from the template that a message was shown that there's no comparable data. The tables seem more informative, so, I'll stick with that for the moment.
This resolves #147.
> Add overview table for missing data

- .dockerignore
- .github/workflows/ci.yml
- .github/workflows/container.yml
- .gitlab-ci.yml
- Dockerfile
- Dockerfile.rebench
- README.md
- docker-compose.yml
- rebench.conf
- src/backend/util.ts
- src/benchmarks/harness.ts
- src/index.ts
- src/shared/errors.ts
This PR changes how the docker-based setup works.
Instead of starting the PostgreSQL server and the Node.js server in the same container, docker-compose.yml defines both as separate containers.
This should improve the ability to use standard docker tooling and container management, and hopefully also avoid issues with the system not starting up properly.
The PR also adds code to wait for Postgres to come up properly, and retry connecting to it.
With Docker, this should be usable with:
```bash
docker compose -f ./docker-compose.yml up
```
For Podman users, podman-compose is needed:
```bash
pip3 install podman-compose  # if not already available
podman-compose up
```
The GitLab CI setup for benchmarking is not using podman-compose, and instead manually starts both containers. Unfortunately, …
> Use Docker Compose and add test that the server comes up

- package.json
- src/backend/db/db.ts
The `needsTables()` was overlooked, and tried to see whether the `Executor` table is there, which is gone since #178, so, it's better to check for the `Run` table instead.
In production, I also had a fix that was not yet in the code base, to copy the shared libraries to the resources folder so that they are available to the browser/user.
> Fix startup after Denormalizing Run table in #178, and make shared libraries available to frontend

- src/frontend/render.ts
- src/index.ts
Looks like rebench.dev is caching a lot of raw data files.
Though, they should only ever be generated when someone actually requested them.
So, it's not clear to me why this happens.
This PR adds three things to hopefully minimize this unnecessary load on the server:
- mark links to data files as `nofollow`
- add the `data` URLs to the disallowed URLs in robots.txt
- ignore browser requests that indicate they are prefetch attempts
> Attempt to reduce unnecessary accesses to data files

- .github/workflows/ci.yml
- src/backend/db/db.ts
- src/backend/dev-server/server.ts
- src/backend/project/data-export.ts
- src/backend/project/project.ts
- src/backend/rebench/results.ts
- src/backend/util.ts
- src/frontend/render.ts
- src/index.ts
- tests/backend/main/main.test.ts
- tests/backend/main/with-data.test.ts
- tests/rebench-integration/check-data.js
- tests/rebench-integration/rebench.conf
- tests/rebench-integration/test-vm.py
This PR adds support to directly export data from Postgres, which avoids Node.js memory limitations. The data is exported as standard CSV file, and compressed with gzip.
Since the data is exported from Postgres, it doesn't need to run through Node.js and JSON conversion first, which enables very large data sets.
To make this work in practice, extra configuration may be necessary when for instance Postgres runs in a container. Generally, it's assume that all data files end up in the same folder.
For this purpose, there are two new environment variables:
- `RDB_DATA_EXPORT_PATH` the path as seen from Postgres
- `NODE_DATA_EXPORT_PATH` the path as seen from Node.js, all files are assume to be accessible by Node.js or the web server to serve them to the client
This is now tested on github …
> Add CSV data export directly from Postgres, and add integration test

- Dockerfile
- package-lock.json
- src/backend/compare/charts.ts
- src/index.ts
- tests/backend/compare/charts.test.ts
- tests/backend/compare/compare-view.test.ts
- tests/backend/compare/prep-data.test.ts
I was a bit too eager and didn't notice that benchmarking was broken for #190, which fixed memory leaks as noticed in #188.
This PR fixes the initialization of ChartJS, doing it now unconditionally when even the relevant code is loaded.
This PR also fixes the Dockerfile so that the patching from #190 also works.
And with that, we see that results are generated now in 22%-40% less time:
https://rebench.dev/ReBenchDB/compare/b0b149a77371ca2e685cf0aab786a32ec26ca958..55c5c5d7ba7d1f6cd4ebbef5febae9bd3bd40539
> Fix chartjs init for benchmark

- package.json
- src/backend/compare/charts.ts
- src/backend/compare/html/gen-index.html
- src/backend/compare/prep-data.ts
This allows the report to render when there's not actually a comparison, but only a single data series.
The PR also reduces the refresh rate of the report-rending placeholder to 5 seconds, since they render so fast now 🥳 
And, we make download of the font conditional on whether it's not already there. Useful for development setup.
This resolves #189.
> Fix report rendering when executor comparison inline plot only has one data series

- .github/workflows/ci.yml
- src/backend/db/db.ts
- src/backend/project/data-export.ts
The CSV export had issues with the files not having the right access permissions, and the redirection to the data file would go to the wrong URL for both JSON and CSV data exports.
> Fix CSV data export file accessibility

- src/backend/compare/compare.ts
- src/frontend/plots.ts
- src/shared/view-types.ts
- tests/backend/compare/db-measurements.test.ts
- tests/backend/db/db-setup.test.ts
- tests/backend/db/db-testing.ts
- tests/backend/db/db.test.ts
- tests/backend/main/with-data.test.ts
- tests/backend/rebench/api.test.ts
- tests/payload.ts
This addresses part of #194.
The SQL that `getMeasurements()` used was not yet adapted to the using an array of values in the database (#100).
This adds now a minimal test, and fixes the SQL.
The PR also:
- introduces `loadSmallPayload()` for consistency
- and makes connection refused errors more easily recognizable in tests
> Fix getMeasurements(), which retrieves the invocation details for the compare view

- src/backend/timeline/timeline.html
- tests/data/expected-results/timeline/index.html
The timeline view is based on the timeline data, which is only computed for the `baseBranch` configured for the project.
This change shows the configuration on the timeline view, or reports that it's missing.
This fixes #196.
> Improve error on timeline view to indicate missing configuration

- src/backend/db/db.ts
- src/backend/project/data-export.ts
Before this PR, we used the project name, which can contain arbitrary unsafe characters.
Though, the project slug is already safe.
So, we just use that one.
It's safe, because projects are created in `recordProject()` with
```sql
INSERT INTO Project (name, slug)
VALUES ($1, regexp_replace($2, '[^0-9a-zA-Z-]', '-', 'g'))
RETURNING *
```
This means, all none number and a-z characters are replaced with `-` and made safe.
See https://github.com/smarr/ReBenchDB/blob/f84de3f1f6cf4f77a4639cc170999d5e129c1e5b/src/backend/db/db.ts#L496-L509
> Fix CSV Data File export (Resolves #198)

- src/backend/compare/compare.ts
- src/backend/main/main.ts
- src/backend/project/data-export.ts
- src/backend/request-check.ts
- src/backend/timeline/timeline.ts
- src/shared/data-format.ts
The rebench.dev errors logs show some invalid requests, which are now hopefully rejected earlier.
It also shows some issue in rendering a template because of an issue in asHumanHz where `h.toFixed` is not a function. I assume that's because `h` is of a wrong type somehow.
> Handle invalid requests and make asHumanHz a bit more robust

- Dockerfile.rebench
- src/backend/compare/compare.ts
Previously, the refresh still used the old url, which used the project name instead of the slug that is now used consistently.
@F12-Syntex perhaps something that caused issues for you.
> Update the redirect on refreshing a report to use the curent URL

- .gitignore
- resources/style.css
- src/backend/compare/html/index.html
- src/frontend/compare.ts
Improved the usability of the compare view by introducing a "Show More" link for the "Changes in Benchmark Set" table. Key enhancements include:
- **Initial Display**: The table now initially displays only 3 entries to prevent overwhelming the user with large datasets.
- **Show More Link**: Added a "Show More" link below the table, allowing users to expand and view all entries on demand.
- **CSS Class**: Introduced a `.hidden` class in `style.css` to manage the visibility of additional table rows.
- **JavaScript Function**: Implemented a `showAllResults` function to handle the display of all entries when the "Show More" link is clicked.
> Implement #206: Add "Show More" for Table with Changes in Benchmark Set in Compare View

- resources/style.css
- src/backend/main/main.ts
- src/backend/project/project.html
- src/frontend/render.ts
- src/shared/view-types.ts
This PR implements #211.
It provides a list of branches that can be sorted by:
- most recent
- most used
- alphabetic
Selecting a branch filters the changes.
The list of branches itself can be filter by a search field, too.
> Implement Sorting and Filtering of Changes based on Branches

- src/frontend/render.ts
The ordering was switched, and showed least-used first.
> Fix order of most used sorting of branches

- resources/style.css
- src/backend/compare/html/gen-index.html
- src/backend/compare/html/index.html
- src/backend/compare/html/refresh-menu.html
- src/backend/compare/html/stats-row-buttons-info.html
- src/backend/main/index.html
- src/backend/project/get-exp-data.html
- src/backend/project/project-data.html
- src/backend/project/project.html
- src/backend/timeline/timeline.html
- src/frontend/compare.ts
- src/frontend/render.ts
- src/views/header.html
- tests/data/expected-results/compare-view/compare-versions.html
- tests/data/expected-results/compare-view/stats-row-button-info.html
- tests/data/expected-results/compare-view/stats-row-exe.html
- tests/data/expected-results/compare-view/stats-row-version-one-criteria-missing.html
- tests/data/expected-results/compare-view/stats-row-version.html
- tests/data/expected-results/compare-view/stats-tbl.html
- tests/data/expected-results/main/index.html
- tests/data/expected-results/project/get-exp-data.html
- tests/data/expected-results/project/project-data.html
- tests/data/expected-results/stats-data-prep/compare-view-jssom.html
- tests/data/expected-results/stats-data-prep/compare-view-tsom.html
- tests/data/expected-results/timeline/index.html
This PR updates the Bootstrap version to the latest available version.
To make this work, I need to:
- replace the removed jumbotron with a custom verion
- use namespaced data attributes (data-bs-toggle, data-bs-target, data-bs-content) where I use features such as collapse, list, and popover.
- adapt CSS for 2/3 width to work with new version
Additionally, I fixed an issue with the commit message expansion on the data papge.
> Update Bootstrap to 5.3.3
